### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by mekolat** [mekolat/tmw-stats#2]
- [ ] maybe switch to Angular if this project gets too big
- [ ] fallback to `sessionStorage` if `localStorage` is not available
- [ ] Profiles
   - [x] use profiles internally
   - [ ] add the profiles table in `#container`
   - [ ] allow to add a new profile
   - [ ] allow to delete a profile
   - [ ] allow to choose a profile from the profile list
   - [ ] allow to give a name to a profile
- [ ] catalog (**maybe as a separate project**)
   - [ ] add the stats of popular players to the catalog
   - [ ] use `Raphael` or `d3` to draw radar charts
